/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import controller.Controller;
import javax.swing.JOptionPane;
import server_paket.PokretanjeServera;

/**
 *
 * @author Korisnik
 */
public class MainForm extends javax.swing.JFrame {

    PokretanjeServera ps = null;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        Controller.getInstance().setSf(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("POKRENI SERVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Klik za pokretanje servera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ps = new PokretanjeServera();
        ps.start();
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void dobroPokretanje() {
        JOptionPane.showMessageDialog(this, "SERVER USPESNO POKRENUT", "USPESNO POKRETANJE", JOptionPane.INFORMATION_MESSAGE);
    }

    public void losePokretanje(String message) {
        JOptionPane.showMessageDialog(this, "GRESKA PRI POKRETANJU SERVERA: "+message, "GRESKA", JOptionPane.ERROR_MESSAGE);
    }

    public void povezanKlijent() {
        JOptionPane.showMessageDialog(this, "KLIJENT BROJ "+Controller.getInstance().getBrojKorinika()+" USPESNO POVEZAN", "USPESNO POVEZIVANJE", JOptionPane.INFORMATION_MESSAGE);
    }

    public void greskaKlijent(String message) {
        JOptionPane.showMessageDialog(this, "GRESKA PRI POVEZIVANJU KLIJENTA: "+message, "GRESKA", JOptionPane.ERROR_MESSAGE);
    }

    public void greskaPriCitanjuZahteva(String message) {
        JOptionPane.showMessageDialog(this, "GRESKA PRI CITANJU KLIJENTSKOG ZAHTEVA: "+message, "GRESKA", JOptionPane.ERROR_MESSAGE);
    }

    public void greskaPriSlanjuOdgovora(String message) {
        JOptionPane.showMessageDialog(this, "GRESKA PRI SLANJU SERVERSKOG ODGOVORA: "+message, "GRESKA", JOptionPane.ERROR_MESSAGE);
    }
}
