/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.List;
import klase_za_mreznu_komunikaciju.ClientRequest;
import klase_za_mreznu_komunikaciju.ServerResponse;
import komunikacija.Komunikacija;
import model.Prijava;
import model.Putnik;
import operacije.Operacije;

/**
 *
 * @author Korisnik
 */
public class MeniForma extends javax.swing.JFrame {

    private Putnik ulogovaniPutnik;

    /**
     * Creates new form MeniForma
     */
    public MeniForma() {
        initComponents();
        ulogovaniPutnik = Komunikacija.getInstance().getUlogovaniPutnik();
        jLabelKorisnik.setText(ulogovaniPutnik.toString());
        jTablePrijave.setVisible(false);
        jLabelNaslov.setVisible(false);
        jLabelText.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelKorisnik = new javax.swing.JLabel();
        jLabelNaslov = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrijave = new javax.swing.JTable();
        jButtonNovaPrijava = new javax.swing.JButton();
        jLabelText = new javax.swing.JLabel();
        jButtonPrikaziPrijave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Zdravo, ");

        jLabelKorisnik.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabelNaslov.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNaslov.setText("PRIKAZ VASIH PRIJAVA:");

        jTablePrijave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePrijave);

        jButtonNovaPrijava.setText("NOVA PRIJAVA");
        jButtonNovaPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaPrijavaActionPerformed(evt);
            }
        });

        jLabelText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelText.setText("Klikom na odgovarajuca polja mozete izmeniti dostupne prijave koje su U OBRADI!");

        jButtonPrikaziPrijave.setText("PRIKAZI PRIJAVE");
        jButtonPrikaziPrijave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPrijaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelText)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNaslov)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jButtonPrikaziPrijave)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonNovaPrijava)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelKorisnik)
                    .addComponent(jButtonPrikaziPrijave)
                    .addComponent(jButtonNovaPrijava))
                .addGap(22, 22, 22)
                .addComponent(jLabelNaslov)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelText)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovaPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaPrijavaActionPerformed
        PrijavaPutovanja pp = new PrijavaPutovanja(ulogovaniPutnik);
        pp.setVisible(true);
    }//GEN-LAST:event_jButtonNovaPrijavaActionPerformed

    private void jButtonPrikaziPrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPrijaveActionPerformed
        // TODO add your handling code here:
        prikaziTabelu();
    }//GEN-LAST:event_jButtonPrikaziPrijaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeniForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNovaPrijava;
    private javax.swing.JButton jButtonPrikaziPrijave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKorisnik;
    private javax.swing.JLabel jLabelNaslov;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrijave;
    // End of variables declaration//GEN-END:variables

    private void prikaziTabelu() {

        jLabelNaslov.setVisible(true);
        jLabelText.setVisible(true);
        ClientRequest rq = new ClientRequest(ulogovaniPutnik, Operacije.VRATI_PUTOVANJA);
        Komunikacija.getInstance().posaljiZahtev(rq);

        ServerResponse sr = Komunikacija.getInstance().primiOdgovor();
        List<Prijava> listaPrijava = (List<Prijava>) sr.getResponse();

        ModelTabelePrijava mtp = new ModelTabelePrijava(listaPrijava);
        jTablePrijave.setModel(mtp);
        jTablePrijave.setVisible(true);
    }

}
